apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${VOLUME_NAME_CFG}-pv
  namespace: ${P_NAMESPACE}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "${VOLUME_DIR_CFG}"